// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCpQx7lN-kHQLjPAZfPUd0FX9csVSTsR4',
    appId: '1:364984232490:web:d763ff570f9e6d35e2f153',
    messagingSenderId: '364984232490',
    projectId: 'berita-pab',
    authDomain: 'berita-pab.firebaseapp.com',
    storageBucket: 'berita-pab.firebasestorage.app',
    measurementId: 'G-TST43B9E88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnnOXhRm8tkWuvVMpZQ1uEQ_F_LLJU1v4',
    appId: '1:364984232490:android:06b8028fd6d22983e2f153',
    messagingSenderId: '364984232490',
    projectId: 'berita-pab',
    storageBucket: 'berita-pab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATfXVTjmkNKZ0LxLrmw62U4FWiUGWbFOU',
    appId: '1:364984232490:ios:50c0ffbbb20a9687e2f153',
    messagingSenderId: '364984232490',
    projectId: 'berita-pab',
    storageBucket: 'berita-pab.firebasestorage.app',
    iosBundleId: 'com.example.flutterPertemuan1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATfXVTjmkNKZ0LxLrmw62U4FWiUGWbFOU',
    appId: '1:364984232490:ios:50c0ffbbb20a9687e2f153',
    messagingSenderId: '364984232490',
    projectId: 'berita-pab',
    storageBucket: 'berita-pab.firebasestorage.app',
    iosBundleId: 'com.example.flutterPertemuan1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCpQx7lN-kHQLjPAZfPUd0FX9csVSTsR4',
    appId: '1:364984232490:web:2d463d8839a09f48e2f153',
    messagingSenderId: '364984232490',
    projectId: 'berita-pab',
    authDomain: 'berita-pab.firebaseapp.com',
    storageBucket: 'berita-pab.firebasestorage.app',
    measurementId: 'G-E5VLDY0RGK',
  );
}
